In [37]:
import numpy as np

In [39]:
# 1. Test whether none of the elements of a given array is zero
def test_no_zero(array):
    return np.all(array != 0)

# Example
array_example1 = np.array([1, 2, 3])
print("None of the elements are zero:", test_no_zero(array_example1))

None of the elements are zero: True


In [41]:
# 2. Test whether any of the elements of a given array is non-zero
def test_any_non_zero(array):
    return np.any(array != 0)

# Example
array_example2 = np.array([0, 0, 3])
print("Any element is non-zero:", test_any_non_zero(array_example2))

Any element is non-zero: True


In [43]:
# 3. Element-wise comparison of two arrays (equal, equal within tolerance)
def compare_arrays(arr1, arr2):
    exact = np.array_equal(arr1, arr2)
    close = np.allclose(arr1, arr2)
    return exact, close

# Example
arr1 = np.array([1.0, 2.0, 3.0])
arr2 = np.array([1.0, 2.0, 3.001])
print("Comparison (exact, close):", compare_arrays(arr1, arr2))

Comparison (exact, close): (False, False)


In [45]:
# 4. Create an array of 10 zeros, 10 ones, and 10 fives
array_zeros_ones_fives = np.concatenate((np.zeros(10), np.ones(10), np.full(10, 5)))

# Example
print("Array of 10 zeros, 10 ones, and 10 fives:", array_zeros_ones_fives)


Array of 10 zeros, 10 ones, and 10 fives: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [47]:
# 5. Create an array of integers from 30 to 70
array_30_to_70 = np.arange(30, 71)

# Example
print("Array from 30 to 70:", array_30_to_70)

Array from 30 to 70: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [49]:
# 6. Create a 3x3 identity matrix
identity_matrix = np.eye(3)

# Example
print("3x3 Identity Matrix:\n", identity_matrix)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
# 7. Generate a random number between 0 and 1
random_number = np.random.rand()

# Example
print("Random number between 0 and 1:", random_number)


Random number between 0 and 1: 0.3837319965186333


In [53]:
# 8. Generate an array of 15 random numbers from a standard normal distribution
random_normal_array = np.random.randn(15)

# Example
print("15 random numbers from standard normal distribution:", random_normal_array)


15 random numbers from standard normal distribution: [-0.09708278 -0.84793818  0.11980281  0.5295909  -0.19837183 -1.61300516
 -0.02974994  0.42402975  1.40087503  2.00874418 -0.32011147 -0.02534397
 -0.71999993 -0.55456636  0.5859385 ]


In [55]:
# 9. Create a vector with values from 15 to 55, excluding the first and last
vector_15_to_55 = np.arange(15, 56)[1:-1]

# Example
print("Vector from 15 to 55 excluding first and last:", vector_15_to_55)


Vector from 15 to 55 excluding first and last: [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [57]:
# 10. Create a vector of length 5 filled with arbitrary integers from 0 to 10
vector_random_integers = np.random.randint(0, 11, 5)

# Example
print("Vector of 5 random integers from 0 to 10:", vector_random_integers)


Vector of 5 random integers from 0 to 10: [6 7 3 6 5]


In [59]:
# 11. Create a 10x10 matrix with border elements as 1 and inside as 0
border_matrix = np.ones((10, 10))
border_matrix[1:-1, 1:-1] = 0

# Example
print("10x10 Matrix with border as 1 and inside as 0:\n", border_matrix)


10x10 Matrix with border as 1 and inside as 0:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [61]:
# 12. Create a 5x5 zero matrix with main diagonal elements as 1, 2, 3, 4, 5
diagonal_matrix = np.zeros((5, 5))
np.fill_diagonal(diagonal_matrix, np.arange(1, 6))

# Example
print("5x5 Matrix with diagonal 1 to 5:\n", diagonal_matrix)


5x5 Matrix with diagonal 1 to 5:
 [[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [63]:
# 13. Create a 4x4 matrix with 0 and 1 staggered, zeros on the main diagonal
staggered_matrix = np.zeros((4, 4), dtype=int)
staggered_matrix[::2, 1::2] = 1
staggered_matrix[1::2, ::2] = 1

# Example
print("4x4 Staggered Matrix:\n", staggered_matrix)

4x4 Staggered Matrix:
 [[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [65]:
# 14. Save two arrays into a single compressed file and load it
def save_and_load_arrays(arr1, arr2):
    np.savez_compressed('arrays_compressed.npz', array1=arr1, array2=arr2)
    data = np.load('arrays_compressed.npz')
    return data['array1'], data['array2']

# Example
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
saved_arrays = save_and_load_arrays(array1, array2)
print("Loaded arrays:", saved_arrays)

Loaded arrays: (array([1, 2, 3]), array([4, 5, 6]))


In [67]:
# 15. Create a one-dimensional array of 40 pseudo-randomly generated values
random_array_40 = np.random.rand(40)

# Example
print("40 random values:", random_array_40)

40 random values: [0.44216612 0.31627777 0.86021563 0.96450698 0.35526888 0.772797
 0.67112623 0.22046776 0.90464083 0.99327643 0.12206223 0.6589081
 0.58213562 0.77340508 0.74926088 0.46672547 0.08293772 0.89792565
 0.92537032 0.51222065 0.76493986 0.73731602 0.41422638 0.76848847
 0.30081417 0.4345995  0.07750654 0.52581794 0.01118877 0.72057608
 0.4538286  0.04184649 0.05032932 0.0497849  0.29707126 0.35509809
 0.42755042 0.97671173 0.77688831 0.40766613]


In [69]:
# 16. Extract all numbers from a given array less and greater than a specified number
def extract_by_condition(array, low, high):
    return array[(array < low) | (array > high)]

# Example
array_example3 = np.array([10, 20, 30, 40, 50])
print("Extracted values:", extract_by_condition(array_example3, 15, 45))


Extracted values: [10 50]
